general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: aimlapi/claude/claude-3-5-haiku
    litellm_provider: aimlapi
    litellm_params:
      model: claude-3-5-haiku-20241022
      api_key: ${AI_ML_API_KEY}
      api_base: https://api.aimlapi.com/v1
      authorization_type: bearer
      model_response_format: openai  # 👈 needs to be inside here

litellm_settings:
  drop_params: true



