general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: vertex-claude
    litellm_params:
      model: claude-3-5-haiku@20241022
      api_base: https://us-central1-aiplatform.googleapis.com/v1
      api_version: v1

  - model_name: vertex-llama
    litellm_params:
      model: llama-4-scout-17b-16e-instruct-maas
      api_base: https://us-central1-aiplatform.googleapis.com/v1
      api_version: v1

litellm_settings:
  drop_params: true
  #success_callback: ["prometheus"]
  #failure_callback: ["prometheus"]
  #service_callback: ["prometheus_system"]

