general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: claude-haiku
    litellm_provider: aiml
    litellm_params:
      model: anthropic/claude-3.5-haiku
      api_key: ${AI_ML_API_KEY}

litellm_settings:
  drop_params: true

