general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: claude-haiku
    litellm_provider: aimm
    litellm_params:
      model: anthropic/claude-3.5-haiku
      api_key: ${AIMM_API_KEY}

  - model_name: llama-hf
    litellm_provider: huggingface
    litellm_params:
      model: meta-llama/Llama-4-Maverick-17B-128E-Instruct
      api_key: ${HF_API_KEY}

litellm_settings:
  drop_params: true
  # success_callback: ["prometheus"]  # Keep these lines commented out for now
  # failure_callback: ["prometheus"]
  # service_callback: ["prometheus_system"]

