general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: claude-haiku
    litellm_provider: aimm
    litellm_params:
      model: anthropic/claude-3.5-haiku
      api_key: ${AIMM_API_KEY}

  - model_name: llama-scout
    litellm_provider: vertex_ai
    litellm_params:
      model: publishers/meta/models/llama-4-scout-17b-16e-instruct-maas
      project: lumie-nexus-bridge
      location: us-central1

litellm_settings:
  drop_params: true
