general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: "claude-3-5-haiku"
    litellm_params:
      model: "claude-3-5-haiku@20241022"

  - model_name: "llama-4-scout"
    litellm_params:
      model: "llama-4-scout-17b-16e-instruct-maas"

litellm_settings:
  drop_params: true
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
  service_callback: ["prometheus_system"]
